version: '3'

networks:
  graynet:
    driver: bridge

# This is how you persist data between container restarts
volumes:
  mongo_data:
    driver: local
  log_data:
    driver: local
  graylog_data:
    driver: local

services:

  # Graylog stores configuration in MongoDB
  mongo:
    image: mongo:6.0.5-jammy
    container_name: mongodb
    volumes:
      - "mongo_data:/data/db"
    networks:
      - graynet
    restart: unless-stopped

  # The logs themselves are stored in Opensearch
  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
    volumes:
      - "/mnt/log_data:/usr/share/opensearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200/tcp
    networks:
      - graynet
    restart: unless-stopped

  graylog:
    image: graylog/graylog:5.1
    container_name: graylog
    environment:
      # CHANGE ME (must be at least 16 characters)!
      # Used for Graylog password_secret functions, not for login!
      GRAYLOG_PASSWORD_SECRET: "ChangeMe"
      
      # Hashed password for user "admin"
      # Generate SHA2 of "admin" password with command: echo -n YourPassword | shasum -a 256
      GRAYLOG_ROOT_PASSWORD_SHA2: ""
      
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
      GRAYLOG_TIMEZONE: "America/Los_Angeles"
      TZ: "America/Los_Angeles"
      GRAYLOG_TRANSPORT_EMAIL_PROTOCOL: "smtp"
      
      # Change 'district' to name of School District
      GRAYLOG_TRANSPORT_EMAIL_WEB_INTERFACE_URL: "https://graylog-district.ncesd.tech/"
      
      GRAYLOG_TRANSPORT_EMAIL_HOSTNAME: "smtp.office365.com"
      GRAYLOG_TRANSPORT_EMAIL_ENABLED: "true"
      GRAYLOG_TRANSPORT_EMAIL_PORT: "587"
      GRAYLOG_TRANSPORT_EMAIL_USE_AUTH: "true"
      
      # Change username to O365 email address
      GRAYLOG_TRANSPORT_EMAIL_AUTH_USERNAME: ""
      
      # Add O365 email password here
      GRAYLOG_TRANSPORT_EMAIL_AUTH_PASSWORD: ""
      
      GRAYLOG_TRANSPORT_EMAIL_USE_TLS: "true"
      GRAYLOG_TRANSPORT_EMAIL_USE_SSL: "false"
      
      # Change username to O365 email address
      GRAYLOG_TRANSPORT_FROM_EMAIL: ""

      # Change 'district' to name of School District
      GRAYLOG_TRANSPORT_SUBJECT_PREFIX: "[graylog-district]"

    entrypoint: /usr/bin/tini -- wait-for-it opensearch:9200 -- /docker-entrypoint.sh
    volumes:
      - "${PWD}/config/graylog/graylog.conf:/usr/share/graylog/config/graylog.conf"
      - "graylog_data:/usr/share/graylog/data"
    networks:
      - graynet
    restart: always
    depends_on:
      opensearch:
        condition: "service_started"
      mongo:
        condition: "service_started"
    ports:
      - 9000:9000/tcp   # Graylog web interface and REST API
      - 514:1516/udp    # Cisco Syslog
      - 1514:1514/tcp   # Syslog
      - 1514:1514/udp   # Syslog
      - 12201:12201/tcp # GELF
      - 12201:12201/udp # GELF
      - 1515:1515/udp   # Synology NAS
      - 1517:1517/udp   # APC Managment Cards
      - 5044:5044/tcp   # Windows DCs
      - 5045:5045/tcp   # Windows Member Servers
      - 5046:5046/tcp   # Windows Hyper-V Hosts
